name: Auto-Update IPA Archive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install remotezip

      - name: Install ImageOptim CLI
        run: |
          brew update
          brew install imageoptim-cli

      - name: Archive → update & run (ignore errors)
        run: |
          set +e
          python3 ipa_archive.py update
          python3 ipa_archive.py run
          set -e

      - name: Optimize images
        run: ./tools/image_optim.sh

      - name: Reset any fixable errors (so they’ll be re-queued)
        run: python3 ipa_archive.py err reset || true

      - name: Export JSON index
        run: python3 ipa_archive.py export json

      - name: Convert all done=0 plists to XML
        run: |
          for id in $(sqlite3 archive.db "SELECT base_url_id FROM archive WHERE done=0;"); do
            ./tools/convert_plist.sh "$id" || true
          done

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "auto archive update [skip ci]"
          git push
